python examples using clustering
tahini/tracecompass-ease-scripting pull request #2
Opened 2019-12-02 17:47 UTC by damadux

Adds 2 python scripts using clustering libraries from SciPy and Sklearn. The analysis clusters system calls based on their duration, then outputs a xy graph with matplotlib (x for system call duration, y for system call name).

2019-12-02 20:05 UTC, tahini requested changes
Thanks for the scripts! It's great to have example of ML libraries with trace data!

Some comments though.

Also, I know these are meant to be examples scripts, but I am not very familiar with ML and the output of those example scripts has no meaning to me:

For example, "{'ioctl': 0, 'splice': 1, 'sync_file_range2': 2, 'arm_fadvise64_64': 3, 'clock_gettime': 4, 'read': 5...", I don't know what it means. But I get errors, maybe there is supposed to be more outputs after that? Anyway, if you could provide some insight in the output, something that will help lay[wo]men make sense of this example, that would be great!

2019-12-02 20:05 UTC, tahini commented on examples/python/kMeanClusteringSciPy.py
> +# Imports
Please add a copyright header at the top of the file. Also more comments for the users of this file, as some may go straight to this and not necessarily pass by the README beforehand. The header should explain what this file does, what trace it runs on and any setup required to run it properly.

2019-12-02 20:05 UTC, tahini commented on README.md
> + - **examples/python/[kMeanClusteringSciPy.py](examples/python/kMeanClusteringSciPy.py)** and **examples/python/[kMeanClusteringSciPy.py](examples/python/kMeanClusteringSklearn.py)**: Works with kern
"Additionally <scipy> uses the scipy library, while <sklean> uses the scikit-learn library".

To describe the argument, look at the https://github.com/tahini/tracecompass-ease-scripting/blob/master/utils/javascript/exportUstSymbols.js script, where the header has the information for the expected arguments. It isn't clear here what it means. And give an example of usage, or a suggested value.

2019-12-02 20:05 UTC, tahini commented on examples/python/kMeanClusteringSciPy.py
> +# Imports
You can add an MIT license like this:

```
# The MIT License (MIT)
#
# Copyright (C) 2019 - You
#
```

2019-12-02 20:05 UTC, tahini commented on examples/python/kMeanClusteringSciPy.py
> +pyplot.show()
With an argument of 3, I get the following error:
org.eclipse.ease.ScriptExecutionException: Traceback (most recent call last):
  File "workspace://test traces/kMeanClustringSciPy.py", line 130, in <module>
    if converter.can_convert(value):
  File "/usr/lib/python3.8/site-packages/matplotlib/pyplot.py", line 269, in show
    return _show(*args, **kw)
  File "/usr/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 413, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3302, in show
    cls.mainloop()
  File "/usr/lib/python3.8/site-packages/matplotlib/backends/backend_qt5.py", line 1094, in mainloop
    signal.signal(signal.SIGINT, signal.SIG_DFL)
  File "/usr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

What am I doing wrong?

2019-12-02 20:05 UTC, tahini commented on examples/python/kMeanClusteringSciPy.py
> +	for i in range(int(argv[0])):
A good practice would be to start the script by verifying that an argument is present and print an error message if there is none, explaining the argument required.

2020-01-17 19:15 UTC, tahini commented
With new updates with py4j vs jython scripting engine, these scripts are good examples of mixed engine scripts, and I managed to have them working properly with python2. So I'll re-work then with that in mind and merge this PR.

Then we can document that it works only with python2? or you tell me why it does not work with python 3. And let's fix it if possible!

2020-01-20 21:24 UTC, tahini commented
@damadux Could you take a look at the damadux-master branch that I update in this repo? If it's ok with you, I'll merge it with master and close this PR. Thanks!

2020-01-21 15:14 UTC, damadux commented
Looks good! I will test these with py4j and jython.

2020-01-21 18:34 UTC, merged

2020-01-21 18:36 UTC, tahini commented
now merged. Thanks! Test it please, I'll let you figure out how to do so, from the doc and eventual output messages. If it's not clear, patches welcome!

2020-01-21 18:47 UTC, damadux commented
Did you still have an error running these examples with Python 3? I had no issues with my machine.

2020-01-21 19:26 UTC, tahini commented
Yes, but setting this: matplotlib.use("GTK3Agg")    fixed it. It was using Qt5 backend I think and there there is a signal that needs to be run from the UI thread. So it's not really python3 problem after all, but pyplot backend. The script in master has that fix.