WIP: Add marker examples for javascript and python
tahini/tracecompass-ease-scripting pull request #3
Opened 2020-03-24 19:16 UTC by gpollo

This simple example computes the region of 5 ms containing the most
`sched_switch` events and highlights it using a marker.

Signed-off-by: Gabriel-Andrew Pollo-Guilbert <gabrielpolloguilbert@gmail.com>

2020-04-01 13:55 UTC, tahini commented
Could you try to make the python script run with jython instead of py4j? Jython is much more performant for our purposes. As proof, see http://versatic.net/tracecompass/scriptEngineBenchmarks.html

2020-05-08 15:42 UTC, tahini requested changes
Thanks for this, javascript works great. Python, not as great. You can either fix the python script or separate javascript and python PR and I can merge the javascript one and eventually debug the python one.

2020-05-08 15:42 UTC, tahini commented on examples/python/marker.py
> +analysis = getActiveTrace()
trace =

2020-05-08 15:42 UTC, tahini commented on examples/python/marker.py
> +                pass
This try catch hides an exception in the trace. Removing this, I get the following exception:

org.eclipse.ease.ScriptExecutionException: Traceback (most recent call last):
  File "workspace://test_traces/marker.py", line 98, in <module>
  File "workspace://test_traces/marker.py", line 89, in runAnalysis
  File "workspace://test_traces/marker.py", line 60, in updateMostEventful
  File "/home/gen/workspace/Dorsal/tcincu-workspace/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/py4j-python_0.10.8.1-bnd-2odeag/src/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/gen/workspace/Dorsal/tcincu-workspace/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/py4j-python_0.10.8.1-bnd-2odeag/src/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
Py4JError: An error occurred while calling o34.getTimestamp. Trace:
py4j.Py4JException: Target Object ID does not exist for this gateway :o34
	at py4j.Gateway.invoke(Gateway.java:279)

And the marker that I get is the first one only, ie not the same as the javascript marker

2020-05-08 16:06 UTC, gpollo commented
Alright, I'll put the python example in a separate PR.

2020-05-08 16:12 UTC, merged

2020-05-08 16:12 UTC, tahini commented
Thanks!